
import TestImage from './test-image.jpg';
import HeaderImg from './halftone-test2.png';

const projects = [

    {
      number:"1/6",
      path:'/project-1',
      title: "Project Title 1",
      year: "2024",
      id: 1,
      source: TestImage,
      tags: ["information design", "graphic design", "ux research"],
      description: "Very short description about the project. Might go upto a second line, partly. Perhaps a little more.",
      headerImg: HeaderImg,
      about: "All about project 1",
      brief: "This is the first project's brief.",
      deliverables: "Something, more stuff, final stuff",
      duration: "6 months",
    },
    {
      number:"2/6",
      path:'/project-2',
      title: "Project Title 2",
      year: "2023",
      id: 2,
      source: TestImage,
      tags: ["information design", "graphic design", "ux research"],
      description: "Very short description about the project. Might go upto a second line, partly. Perhaps a little more.",
      headerImg: HeaderImg,
      about: "All about project 2",
      brief: "This is the second project's brief.",
      deliverables: "Something, more stuff, final stuff",
      duration: "5 months",
    },
    {
      number:"3/6",
      path:'/{project-3}',
      title: "Project Title 3",
      year: "2022",
      id: 3,
      source: TestImage,
      tags: ["information design", "graphic design", "ux research"],
      description: "Very short description about the project. Might go upto a second line, partly. Perhaps a little more.",
      headerImg: HeaderImg,
      about: "All about project 3",
      brief: "This is the third project's brief.",
      deliverables: "Something, more stuff, final stuff",
      duration: "4 months",
    },
    {
      number:"4/6",
      path:'/project-4',
      title: "Project Title 4",
      year: "2022",
      id: 4,
      source: TestImage,
      tags: ["information design", "graphic design", "ux research"],
      description: "Very short description about the project. Might go upto a second line, partly. Perhaps a little more.",
      headerImg: HeaderImg,
      about: "All about project 4",
      brief: "This is the fourth project's brief.",
      deliverables: "Something, more stuff, final stuff",
      duration: "3 months",
    },
    {
      number:"5/6",
      path:'/project-5',
      title: "Project Title 5",
      year: "2021",
      id: 5,
      source: TestImage,
      tags: ["information design", "graphic design", "ux research"],
      description: "Very short description about the project. Might go upto a second line, partly. Perhaps a little more.",
      headerImg: HeaderImg,
      about: "All about project 5",
      brief: "This is the fifth project's brief.",
      deliverables: "Something, more stuff, final stuff",
      duration: "2 months",
    },
    {
      number:"6/6",
      path:'/project-6',
      title: "Project Title 6",
      year: "2021",
      id: 6,
      source: TestImage,
      tags: ["information design", "graphic design", "ux research"],
      description: "Very short description about the project. Might go upto a second line, partly. Perhaps a little more.",
      headerImg: HeaderImg,
      about: "All about project 6",
      brief: "This is the sixth project's brief.",
      deliverables: "Something, more stuff, final stuff",
      duration: "1 month",
    }
  ];

  export default projects;